name: "Discord Releases"

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    name: Discord Releases Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "41214"
          username: ${{ github.event.repository.name }}
          avatar_url: "https://r2.fivemanage.com/xm6joUUSlUjI3K1Qfndbd/logo-1024x1024.png"
          content: "<@&${{ secrets.ROLE_ID }}> New Release Published!"
          footer_timestamp: true
